parameters:
#    srcsalle.example.class: src\salleBundle\Example

services:
#    srcsalle.example:
#        class: %srcsalle.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
