<?php

namespace Proxies\__CG__\src\salleBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Sport extends \src\salleBundle\Entity\Sport implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getIdSport()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["idSport"];
        }
        $this->__load();
        return parent::getIdSport();
    }

    public function setNomS($nomS)
    {
        $this->__load();
        return parent::setNomS($nomS);
    }

    public function getNomS()
    {
        $this->__load();
        return parent::getNomS();
    }

    public function setNbreHeure($nbreHeure)
    {
        $this->__load();
        return parent::setNbreHeure($nbreHeure);
    }

    public function getNbreHeure()
    {
        $this->__load();
        return parent::getNbreHeure();
    }

    public function setPrix($prix)
    {
        $this->__load();
        return parent::setPrix($prix);
    }

    public function getPrix()
    {
        $this->__load();
        return parent::getPrix();
    }

    public function setIdCoach(\src\salleBundle\Entity\Coach $idCoach = NULL)
    {
        $this->__load();
        return parent::setIdCoach($idCoach);
    }

    public function getIdCoach()
    {
        $this->__load();
        return parent::getIdCoach();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'idSport', 'nomS', 'nbreHeure', 'prix', 'idCoach');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}