<?php

namespace Proxies\__CG__\src\salleBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Coach extends \src\salleBundle\Entity\Coach implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getIdCoach()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["idCoach"];
        }
        $this->__load();
        return parent::getIdCoach();
    }

    public function setNomC($nomC)
    {
        $this->__load();
        return parent::setNomC($nomC);
    }

    public function getNomC()
    {
        $this->__load();
        return parent::getNomC();
    }

    public function setPrenomC($prenomC)
    {
        $this->__load();
        return parent::setPrenomC($prenomC);
    }

    public function getPrenomC()
    {
        $this->__load();
        return parent::getPrenomC();
    }

    public function setNumTelC($numTelC)
    {
        $this->__load();
        return parent::setNumTelC($numTelC);
    }

    public function getNumTelC()
    {
        $this->__load();
        return parent::getNumTelC();
    }

    public function setSalaire($salaire)
    {
        $this->__load();
        return parent::setSalaire($salaire);
    }

    public function getSalaire()
    {
        $this->__load();
        return parent::getSalaire();
    }

    public function setEmail($email)
    {
        $this->__load();
        return parent::setEmail($email);
    }

    public function getEmail()
    {
        $this->__load();
        return parent::getEmail();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'idCoach', 'nomC', 'prenomC', 'numTelC', 'salaire', 'email');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}